from django.db import models

class DisplayCheckType():
    Enclosure = "Enclosure"

class DisplayLine(models.Model):
    id = models.BigAutoField(auto_created=True, primary_key=True)
    lob = models.CharField('lob', null=False, max_length=50)
    site = models.CharField('site', null=True, max_length=50)
    productLine = models.CharField('productLine', null=True, max_length=50)
    project = models.CharField('project', null=True, max_length=50)
    part = models.CharField('part', null=True, max_length=50)
    checkListId_Enclosure = models.BigIntegerField('checkListId_Enclosure', null=True)
    class Meta:
        db_table = 't_display_line'

class DisplayLineConfig(models.Model):
    id = models.BigAutoField(auto_created=True, primary_key=True)
    lob = models.CharField('lob', null=True, max_length=50)
    site = models.CharField('site', null=True, max_length=50)
    productLine = models.CharField('productLine', null=True, max_length=50)
    project = models.CharField('project', null=True, max_length=50)
    part = models.CharField('part', null=True, max_length=50)
    domain = models.CharField('domain', null=False, max_length=50)
    data = models.TextField('data', null=False)
    class Meta:
        db_table = 't_display_line_config'

class DisplayCheckList(models.Model):
    id = models.BigAutoField(auto_created=True, primary_key=True)
    lob = models.CharField('lob', null=False, max_length=50)
    site = models.CharField('site', null=False, max_length=50)
    productLine = models.CharField('productLine', null=False, max_length=50)
    project = models.CharField('project', null=False, max_length=50)
    part = models.CharField('part', null=False, max_length=50)
    type = models.CharField('type', null=False, max_length=50)
    updateTime = models.DateTimeField(null=True)
    createTime = models.DateTimeField(null=True)
    updaterId = models.BigIntegerField('updaterId', null=True)
    updater = models.CharField('updater', null=True, max_length=50)
    class Meta:
        db_table = 't_display_check_list'

class DisplayCheckListItemEnclosure(models.Model):
    id = models.BigAutoField(auto_created=True, primary_key=True)
    checkListId = models.BigIntegerField(null=False)
    sn = models.IntegerField('sn', null=False)
    area = models.CharField('area', null=True, max_length=255)
    mainProcess = models.CharField('mainProcess', null=False, max_length=255)
    subProcess = models.CharField('subProcess', null=False, max_length=255)
    checkItems = models.TextField('checkItems', null=False)
    samplingSize = models.CharField('samplingSize', null=False, max_length=999)
    lookingFor = models.CharField('lookingFor', null=False, max_length=4999)
    recordsFindings = models.CharField('recordsFindings', null=False, max_length=999)
    result = models.CharField('result', null=False, max_length=99)
    auditSampleSize = models.CharField('auditSampleSize', null=False, max_length=255)
    disScore = models.IntegerField('disScore', null=True)
    disTimes = models.IntegerField('disTimes', null=True)
    skip = models.BooleanField('skip', null=True)
    class Meta:
        db_table = 't_display_check_list_item_enclosure'

class DisplayAuditItem(models.Model):
    id = models.BigAutoField(auto_created=True, primary_key=True)
    lob = models.CharField('lob', null=False, max_length=50)
    site = models.CharField('site', null=False, max_length=50)
    productLine = models.CharField('productLine', null=False, max_length=50)
    project = models.CharField('project', null=False, max_length=50)
    part = models.CharField('part', null=False, max_length=50)
    type = models.CharField('type', null=False, max_length=50)
    rawJson = models.TextField('rawJson', null=False)
    beginTime = models.DateTimeField('beginTime', null=False)
    endTime = models.DateTimeField('endTime', null=False)
    uploadTime = models.DateTimeField('uploadTime', null=False)
    updateTime = models.DateTimeField(null=True)
    createTime = models.DateTimeField(null=True)
    auditorId = models.BigIntegerField('auditorId', null=False)
    auditor = models.CharField('auditor', null=False, max_length=50)
    skipCount = models.IntegerField('skipCount', null=False)
    passCount = models.IntegerField('passCount', null=False)
    failCount = models.IntegerField('failCount', null=False)
    doneCount = models.IntegerField('doneCount', null=False)
    totalCount = models.IntegerField('totalCount', null=False)
    findingCount = models.IntegerField('findingCount', null=False)
    class Meta:
        db_table = 't_display_audit_item'

class DisplayAuditItemCheckItemEnclosure(models.Model):
    id = models.BigAutoField(auto_created=True, primary_key=True)
    checkListId = models.BigIntegerField(null=True)
    auditItemId = models.BigIntegerField(null=True)
    lob = models.CharField('lob', null=False, max_length=50)
    site = models.CharField('site', null=False, max_length=50)
    productLine = models.CharField('productLine', null=False, max_length=50)
    project = models.CharField('project', null=False, max_length=50)
    part = models.CharField('part', null=False, max_length=50)

    checkItem_sn = models.IntegerField('checkItem_sn', null=False)
    checkItem_area = models.CharField('checkItem_area', null=True, max_length=255)
    checkItem_mainProcess = models.CharField('checkItem_mainProcess', null=False, max_length=255)
    checkItem_subProcess = models.CharField('checkItem_subProcess', null=False, max_length=255)
    checkItem_checkItems = models.TextField('checkItem_checkItems', null=False)
    checkItem_samplingSize = models.CharField('checkItem_samplingSize', null=False, max_length=999)
    checkItem_lookingFor = models.CharField('checkItem_lookingFor', null=False, max_length=4999)
    checkItem_recordsFindings = models.CharField('checkItem_recordsFindings', null=False, max_length=999)
    checkItem_auditSampleSize = models.CharField('checkItem_auditSampleSize', null=False, max_length=255)
    checkItem_disScore = models.IntegerField('checkItem_disScore', null=True)
    checkItem_disTimes = models.IntegerField('checkItem_disTimes', null=True)
    checkItem_skip = models.BooleanField('checkItem_skip', null=True)

    records = models.CharField('records', null=True, max_length=999)
    result = models.CharField('result', null=True, max_length=255)
    findings = models.TextField('findings', null=True)
    hasFindings = models.BooleanField('hasFindings', null=False)
    isSkip = models.BooleanField('isSkip', null=False)
    isDone = models.BooleanField('isDone', null=False)
    status = models.CharField('status', null=True, max_length=50)
    uploadTime = models.DateTimeField('uploadTime', null=False)
    createTime = models.DateTimeField(null=True)
    auditorId = models.BigIntegerField('auditorId', null=False)
    auditor = models.CharField('auditor', null=False, max_length=50)
    class Meta:
        db_table = 't_display_audit_item_check_item_enclosure'

class DisplayMILItem(models.Model):
    id = models.BigAutoField(auto_created=True, primary_key=True)
    auditItemId = models.BigIntegerField('auditItemId', null=True)
    lob = models.CharField('lob', null=False, max_length=50)
    site = models.CharField('site', null=False, max_length=50)
    productLine = models.CharField('productLine', null=False, max_length=50)
    project = models.CharField('project', null=False, max_length=50)
    part = models.CharField('part', null=False, max_length=50)
    type = models.CharField('type', null=False, max_length=50)
    sn = models.IntegerField('sn', null=True)
    year = models.SmallIntegerField('year', null=False)
    month = models.SmallIntegerField('month', null=False)
    week = models.SmallIntegerField('week', null=False)
    day = models.SmallIntegerField('day', null=False)
    quarter = models.SmallIntegerField('quarter', null=False)
    vendor = models.CharField('vendor', null=False, max_length=50)
    factory = models.CharField('factory', null=False, max_length=50)
    projectPart = models.CharField('projectPart', null=False, max_length=50)
    processCategory = models.CharField('processCategory', null=True, max_length=50)
    line = models.CharField('line', null=True, max_length=50)
    station = models.CharField('station', null=True, max_length=50)
    stage = models.CharField('stage', null=True, max_length=50)
    auditTimes = models.SmallIntegerField('auditTimes', null=True)
    productCategory = models.CharField('productCategory', null=True, max_length=50)
    byAuditCategory = models.CharField('byAuditCategory', null=True, max_length=50)
    issueCategory = models.CharField('issueCategory', null=True, max_length=50)
    subCategory = models.CharField('subCategory', null=True, max_length=50)
    issueBrief = models.CharField('issueBrief', null=True, max_length=255)
    keywords = models.CharField('keywords', null=True, max_length=255)
    status = models.SmallIntegerField('status', null=True)
    programRelated = models.CharField('programRelated', null=True, max_length=99)
    severity = models.CharField('severity', null=True, max_length=50)
    findings = models.CharField('findings', null=True, max_length=255)
    containmentAction = models.CharField('containmentAction', null=True, max_length=255)
    failureAnalysisRootCause = models.CharField('failureAnalysisRootCause', null=True, max_length=255)
    correctiveAction = models.CharField('correctiveAction', null=True, max_length=255)
    department = models.CharField('department', null=True, max_length=50)
    vendorDRI = models.CharField('vendorDri', null=True, max_length=50)
    errorProofCategory = models.CharField('errorProofCategory', null=True, max_length=50)
    errorProof = models.CharField('errorProof', null=True, max_length=255)
    cheatingCategory = models.CharField('cheatingCategory', null=True, max_length=50)
    cheatingSubcategory = models.CharField('cheatingSubcategory', null=True, max_length=50)
    cheatingPattern = models.CharField('cheatingPattern', null=True, max_length=255)
    emailDate = models.DateTimeField('emailDate', null=True)
    planClosedDueDate = models.DateTimeField('planClosedDueDate', null=True)
    actualClosedDate = models.DateTimeField('actualClosedDate', null=True)
    dueMonth = models.SmallIntegerField('dueMonth', null=True)
    ifMILResponseDelayed = models.BooleanField('ifMILResponseDelayed', null=True)
    containmentActionDate = models.DateTimeField('containmentActionDate', null=True)
    containmentLTDate = models.DateTimeField('containmentLTDate', null=True)
    ifContainmentDelayed = models.BooleanField('ifContainmentDelayed', null=True)
    FAFinalizedDate = models.DateTimeField('FAFinalizedDate', null=True)
    FAFinalizedLTDate = models.DateTimeField('FAFinalizedLTDate', null=True)
    ifFADelayed = models.BooleanField('ifFADelayed', null=True)
    CAFinalizedDate = models.DateTimeField('CAFinalizedDate', null=True)
    CAFinalizedLTDate = models.DateTimeField('CAFinalizedLTDate', null=True)
    ifCADelayed = models.BooleanField('ifCADelayed', null=True)
    CAClosureDate = models.DateTimeField('CAClosureDate', null=True)
    ifClosureDelayed = models.BooleanField('ifClosureDelayed', null=True)
    FACAScoreByVendorEvaluationGroup = models.CharField('FACAScoreByVendorEvaluationGroup', null=True, max_length=99)
    vendorEvaluationGroupComments = models.CharField('vendorEvaluationGroupComments', null=True, max_length=300)
    appleFirstEvaluationScore = models.CharField('appleFirstEvaluationScore', null=True, max_length=30)
    appleComments = models.CharField('appleComments', null=True, max_length=255)
    FACAReviewTimes = models.SmallIntegerField('FACAReviewTimes', null=True)
    repeatIssue = models.BooleanField('repeatIssue', null=True)
    repeatTime = models.DateTimeField('repeatTime', null=True)
    auditBlockedPartsQty = models.CharField('auditBlockedPartsQty', null=True, max_length=99)
    scrapedQty = models.CharField('scrapedQty', null=True, max_length=99)
    containments = models.TextField('containments', null=True)
    FAs = models.TextField('FAs', null=True)
    CAs = models.TextField('CAs', null=True)
    highlight = models.BooleanField('highlight', null=True)
    highlightDescription = models.CharField('highlightDescription', null=True, max_length=300)
    auditorId = models.BigIntegerField('auditorId', null=True)
    auditor = models.CharField('auditor', null=True, max_length=32)
    createTime = models.DateTimeField(null=True)
    FA = models.CharField('FA', null=True, max_length=500)
    CA = models.CharField('CA', null=True, max_length=500)
    MILDescription = models.CharField('MILDescription', null=True, max_length=500)
    class Meta:
        db_table = 't_display_mil_item'