# Generated by Django 4.0.1 on 2022-02-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MQAServices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(upload_to='History/')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('visitId', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('lob', models.CharField(max_length=50, verbose_name='lob')),
                ('site', models.CharField(max_length=50, verbose_name='site')),
                ('productLine', models.CharField(max_length=50, verbose_name='productLine')),
                ('project', models.CharField(max_length=50, verbose_name='project')),
                ('part', models.CharField(max_length=50, verbose_name='part/color')),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modifyDate', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('path', models.CharField(max_length=100, verbose_name='路径')),
                ('visitJson', models.CharField(max_length=200, verbose_name='visitJson')),
                ('pic', models.CharField(max_length=150, verbose_name='图片文件夹路径')),
                ('video', models.CharField(max_length=150, verbose_name='视频文件夹路径')),
                ('record', models.CharField(max_length=150, verbose_name='record文件夹路径')),
                ('mil', models.CharField(max_length=150, verbose_name='mil文件夹路径')),
            ],
        ),
        migrations.CreateModel(
            name='visitTest',
            fields=[
                ('visitId', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
            ],
        ),
    ]
