# Generated by Django 4.0.1 on 2022-02-21 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MQAServices', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='visitTest',
        ),
        migrations.AlterModelTable(
            name='visit',
            table='Visit',
        ),
    ]
