# Generated by Django 4.0.1 on 2022-02-21 06:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MQAServices', '0003_delete_visittest_alter_visit_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
    ]
