# Generated by Django 4.0.1 on 2022-02-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MQAServices', '0004_upload_createdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='message',
            field=models.CharField(default='', max_length=200, verbose_name='msg'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='file_path',
            field=models.FileField(upload_to='<django.db.models.fields.CharField>History/'),
        ),
    ]
