# Generated by Django 4.0.1 on 2022-02-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MQAServices', '0006_remove_upload_message_alter_upload_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='test',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upload',
            name='test2',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='upload',
            name='file_path',
            field=models.FileField(upload_to=str),
        ),
    ]
