# Generated by Django 4.0.1 on 2022-02-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MQAServices', '0007_upload_test_upload_test2_alter_upload_file_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='test2',
        ),
        migrations.AlterField(
            model_name='upload',
            name='file_path',
            field=models.FileField(upload_to=models.FileField(default='', max_length=200, upload_to='')),
        ),
        migrations.AlterField(
            model_name='upload',
            name='test',
            field=models.FileField(default='', max_length=200, upload_to=''),
        ),
    ]
