# Generated by Django 4.0.1 on 2022-02-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MQAServices', '0008_remove_upload_test2_alter_upload_file_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='test',
        ),
        migrations.AlterField(
            model_name='upload',
            name='file_path',
            field=models.FileField(upload_to='History/'),
        ),
    ]
