# Generated by Django 4.0.1 on 2022-02-22 05:18

import MQAServices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MQAServices', '0009_remove_upload_test_alter_upload_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='fullpath',
            field=models.CharField(default='', max_length=150, verbose_name='完整路径'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='upload',
            name='file_path',
            field=models.FileField(upload_to=MQAServices.models.Upload.image_upload_to),
        ),
    ]
