# Generated by Django 4.0.1 on 2022-02-28 09:01

import MQAServices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MQAServices', '0011_uploadrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadMIL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullpath', models.CharField(max_length=150, verbose_name='完整路径')),
                ('file_path', models.FileField(upload_to=MQAServices.models.UploadMIL.file_upload_to)),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
    ]
