# Generated by Django 4.0.1 on 2022-02-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MQAServices', '0012_uploadmil'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadrecord',
            name='savepath',
            field=models.CharField(default='', max_length=150, verbose_name='完整路径'),
        ),
        migrations.AlterField(
            model_name='uploadrecord',
            name='fullpath',
            field=models.CharField(max_length=150),
        ),
    ]
