# Generated by Django 4.0.5 on 2022-10-23 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws_mqaserver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmil',
            name='savepath',
            field=models.CharField(default='', max_length=150, verbose_name='完整路径'),
        ),
        migrations.AlterField(
            model_name='uploadmil',
            name='fullpath',
            field=models.CharField(max_length=150),
        ),
    ]
