# Generated by Django 4.1.4 on 2022-12-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws_mqaserver', '0004_checklistitemort_alter_checklistitemenclosure_result_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('lob', models.CharField(max_length=50, verbose_name='lob')),
                ('site', models.CharField(max_length=50, verbose_name='site')),
                ('productLine', models.CharField(max_length=50, verbose_name='productLine')),
                ('project', models.CharField(max_length=50, verbose_name='project')),
                ('part', models.CharField(max_length=50, verbose_name='part')),
                ('type', models.SmallIntegerField(verbose_name='type')),
                ('rawJson', models.TextField(verbose_name='rawJson')),
                ('updateTime', models.DateTimeField(null=True)),
                ('createTime', models.DateTimeField(null=True)),
                ('auditorId', models.BigIntegerField(verbose_name='auditorId')),
                ('auditor', models.CharField(max_length=50, verbose_name='auditor')),
            ],
            options={
                'db_table': 't_sa_audit_item',
            },
        ),
        migrations.AddField(
            model_name='checklist',
            name='updater',
            field=models.CharField(max_length=50, null=True, verbose_name='updater'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='updaterId',
            field=models.BigIntegerField(null=True, verbose_name='updaterId'),
        ),
        migrations.AddField(
            model_name='militem',
            name='sn',
            field=models.IntegerField(null=True, verbose_name='sn'),
        ),
        migrations.AlterField(
            model_name='user',
            name='account',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='lob',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(max_length=50),
        ),
    ]
