# Generated by Django 4.1.4 on 2022-12-31 15:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aws_mqaserver', '0005_audititem_checklist_updater_checklist_updaterid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='militem',
            name='auditorName',
        ),
        migrations.RemoveField(
            model_name='militem',
            name='byAuditCategory',
        ),
        migrations.RemoveField(
            model_name='militem',
            name='factory',
        ),
        migrations.RemoveField(
            model_name='militem',
            name='keyWords',
        ),
        migrations.RemoveField(
            model_name='militem',
            name='process',
        ),
        migrations.RemoveField(
            model_name='militem',
            name='productCategory',
        ),
        migrations.RemoveField(
            model_name='militem',
            name='programRelated',
        ),
        migrations.RemoveField(
            model_name='militem',
            name='projectPart',
        ),
        migrations.AddField(
            model_name='audititem',
            name='beginTime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='beginTime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audititem',
            name='endTime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='endTime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='militem',
            name='auditItemId',
            field=models.BigIntegerField(null=True, verbose_name='auditItemId'),
        ),
        migrations.AddField(
            model_name='militem',
            name='auditor',
            field=models.CharField(max_length=32, null=True, verbose_name='auditor'),
        ),
        migrations.AddField(
            model_name='militem',
            name='type',
            field=models.SmallIntegerField(default=0, verbose_name='type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='militem',
            name='FACAReviewTimes',
            field=models.SmallIntegerField(null=True, verbose_name='FACAReviewTimes'),
        ),
        migrations.AlterField(
            model_name='militem',
            name='auditTimes',
            field=models.SmallIntegerField(null=True, verbose_name='auditTimes'),
        ),
        migrations.AlterField(
            model_name='militem',
            name='auditorId',
            field=models.BigIntegerField(null=True, verbose_name='auditorId'),
        ),
        migrations.AlterField(
            model_name='militem',
            name='issueCategory',
            field=models.CharField(max_length=50, null=True, verbose_name='issueCategory'),
        ),
        migrations.AlterField(
            model_name='militem',
            name='line',
            field=models.CharField(max_length=50, null=True, verbose_name='line'),
        ),
        migrations.AlterField(
            model_name='militem',
            name='severity',
            field=models.CharField(max_length=50, null=True, verbose_name='severity'),
        ),
        migrations.AlterField(
            model_name='militem',
            name='stage',
            field=models.CharField(max_length=50, null=True, verbose_name='stage'),
        ),
        migrations.AlterField(
            model_name='militem',
            name='station',
            field=models.CharField(max_length=50, null=True, verbose_name='station'),
        ),
        migrations.AlterField(
            model_name='militem',
            name='subCategory',
            field=models.CharField(max_length=50, null=True, verbose_name='subCategory'),
        ),
        migrations.AddField(
            model_name='militem',
            name='keywords',
            field=models.CharField(max_length=255, null=True, verbose_name='keywords'),
        ),
    ]
