# Generated by Django 4.1.4 on 2023-01-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws_mqaserver', '0008_obaitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='audititem',
            name='doneCount',
            field=models.IntegerField(default=0, verbose_name='doneCount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audititem',
            name='failCount',
            field=models.IntegerField(default=0, verbose_name='failCount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audititem',
            name='findingCount',
            field=models.IntegerField(default=0, verbose_name='findingCount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audititem',
            name='passCount',
            field=models.IntegerField(default=0, verbose_name='passCount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audititem',
            name='totalCount',
            field=models.IntegerField(default=0, verbose_name='totalCount'),
            preserve_default=False,
        ),
    ]
