# Generated by Django 4.1.4 on 2023-01-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws_mqaserver', '0011_user_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='team',
            field=models.CharField(default='MQA', max_length=99),
            preserve_default=False,
        ),
    ]
