# Generated by Django 4.1.4 on 2023-01-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws_mqaserver', '0015_checklistitemdestructive_sn_checklistitemglue_sn'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitemenclosure',
            name='auditSampleSize',
            field=models.CharField(default='', max_length=255, verbose_name='auditSampleSize'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklistitemenclosure',
            name='disScore',
            field=models.IntegerField(null=True, verbose_name='disScore'),
        ),
        migrations.AddField(
            model_name='checklistitemenclosure',
            name='disTimes',
            field=models.IntegerField(null=True, verbose_name='disTimes'),
        ),
        migrations.AddField(
            model_name='checklistitemenclosure',
            name='hidden',
            field=models.BooleanField(null=True, verbose_name='hidden'),
        ),
        migrations.AddField(
            model_name='checklistitemmodule',
            name='auditSampleSize',
            field=models.CharField(default='', max_length=255, verbose_name='auditSampleSize'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklistitemmodule',
            name='disScore',
            field=models.IntegerField(null=True, verbose_name='disScore'),
        ),
        migrations.AddField(
            model_name='checklistitemmodule',
            name='disTimes',
            field=models.IntegerField(null=True, verbose_name='disTimes'),
        ),
        migrations.AddField(
            model_name='checklistitemmodule',
            name='hidden',
            field=models.BooleanField(null=True, verbose_name='hidden'),
        ),
        migrations.AddField(
            model_name='checklistitemort',
            name='disScore',
            field=models.IntegerField(null=True, verbose_name='disScore'),
        ),
        migrations.AddField(
            model_name='checklistitemort',
            name='disTimes',
            field=models.IntegerField(null=True, verbose_name='disTimes'),
        ),
        migrations.AddField(
            model_name='checklistitemort',
            name='hidden',
            field=models.BooleanField(null=True, verbose_name='hidden'),
        ),
    ]
