# Generated by Django 4.1.4 on 2023-01-08 16:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aws_mqaserver', '0016_checklistitemenclosure_auditsamplesize_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistitemglue',
            name='glue',
        ),
        migrations.AddField(
            model_name='audititem',
            name='uploadTime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='uploadTime'),
            preserve_default=False,
        ),
    ]
