# Generated by Django 4.1.4 on 2023-01-10 10:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aws_mqaserver', '0017_remove_checklistitemglue_glue_audititem_uploadtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistitemenclosure',
            name='hidden',
        ),
        migrations.RemoveField(
            model_name='checklistitemmodule',
            name='hidden',
        ),
        migrations.RemoveField(
            model_name='checklistitemort',
            name='hidden',
        ),
        migrations.AddField(
            model_name='audititem',
            name='skipCount',
            field=models.IntegerField(default=0, verbose_name='skipCount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklistitemenclosure',
            name='skip',
            field=models.BooleanField(null=True, verbose_name='skip'),
        ),
        migrations.AddField(
            model_name='checklistitemmodule',
            name='skip',
            field=models.BooleanField(null=True, verbose_name='skip'),
        ),
        migrations.AddField(
            model_name='checklistitemort',
            name='skip',
            field=models.BooleanField(null=True, verbose_name='skip'),
        ),
        migrations.AddField(
            model_name='kappaitem',
            name='uploadTime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='uploadTime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='obaitem',
            name='uploadTime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='uploadTime'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checklistitemenclosure',
            name='area',
            field=models.CharField(max_length=255, null=True, verbose_name='area'),
        ),
        migrations.AlterField(
            model_name='checklistitemenclosure',
            name='checkItems',
            field=models.TextField(verbose_name='checkItems'),
        ),
    ]
