# Generated by Django 4.1.4 on 2023-01-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws_mqaserver', '0018_remove_checklistitemenclosure_hidden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='militem',
            name='byAuditCategory',
            field=models.CharField(max_length=50, null=True, verbose_name='byAuditCategory'),
        ),
        migrations.AddField(
            model_name='militem',
            name='factory',
            field=models.CharField(default='', max_length=50, verbose_name='factory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='militem',
            name='process',
            field=models.CharField(default='', max_length=50, verbose_name='process'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='militem',
            name='productCategory',
            field=models.CharField(max_length=50, null=True, verbose_name='productCategory'),
        ),
        migrations.AddField(
            model_name='militem',
            name='programRelated',
            field=models.CharField(max_length=99, null=True, verbose_name='programRelated'),
        ),
        migrations.AddField(
            model_name='militem',
            name='projectPart',
            field=models.CharField(default='', max_length=50, verbose_name='projectPart'),
            preserve_default=False,
        ),
    ]
