# Generated by Django 4.1.4 on 2023-01-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws_mqaserver', '0019_militem_byauditcategory_militem_factory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='militem',
            name='vendor',
            field=models.CharField(default='', max_length=50, verbose_name='vendor'),
            preserve_default=False,
        ),
    ]
