# Generated by Django 4.1.4 on 2023-01-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws_mqaserver', '0020_militem_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='militem',
            name='FACA',
            field=models.CharField(max_length=500, null=True, verbose_name='FACA'),
        ),
        migrations.AddField(
            model_name='militem',
            name='MILDescription',
            field=models.CharField(max_length=500, null=True, verbose_name='MILDescription'),
        ),
    ]
