# Generated by Django 4.1.4 on 2023-01-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws_mqaserver', '0023_lineconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineconfig',
            name='lob',
            field=models.CharField(max_length=50, null=True, verbose_name='lob'),
        ),
    ]
