# Generated by Django 4.1.4 on 2023-02-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws_mqaserver', '0028_accessoryaudititemcheckitemdestructive_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MDEAuditItemCheckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('checkListId', models.BigIntegerField(null=True)),
                ('auditItemId', models.BigIntegerField(null=True)),
                ('lob', models.CharField(max_length=50, verbose_name='lob')),
                ('site', models.CharField(max_length=50, verbose_name='site')),
                ('productLine', models.CharField(max_length=50, verbose_name='productLine')),
                ('project', models.CharField(max_length=50, verbose_name='project')),
                ('checkItem_sn', models.IntegerField(verbose_name='SN')),
                ('checkItem_station', models.CharField(max_length=99, verbose_name='Station')),
                ('checkItem_process', models.CharField(max_length=99, verbose_name='Process')),
                ('checkItem_productLine', models.CharField(max_length=99, verbose_name='Product line')),
                ('checkItem_project', models.CharField(max_length=99, verbose_name='Project')),
                ('checkItem_checkItem', models.CharField(max_length=999, verbose_name='Check Item')),
                ('checkItem_USL', models.FloatField(verbose_name='USL')),
                ('checkItem_LSL', models.FloatField(verbose_name='LSL')),
                ('value', models.FloatField(null=True, verbose_name='Value')),
                ('status', models.CharField(max_length=50, null=True, verbose_name='status')),
                ('uploadTime', models.DateTimeField(verbose_name='uploadTime')),
                ('createTime', models.DateTimeField(null=True)),
                ('auditorId', models.BigIntegerField(verbose_name='auditorId')),
                ('auditor', models.CharField(max_length=50, verbose_name='auditor')),
            ],
            options={
                'db_table': 't_mde_audit_item_check_item',
            },
        ),
        migrations.CreateModel(
            name='MDEAuditItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('lob', models.CharField(max_length=50, verbose_name='lob')),
                ('site', models.CharField(max_length=50, verbose_name='site')),
                ('productLine', models.CharField(max_length=50, verbose_name='productLine')),
                ('project', models.CharField(max_length=50, verbose_name='project')),
                ('beginTime', models.DateTimeField(verbose_name='beginTime')),
                ('endTime', models.DateTimeField(verbose_name='endTime')),
                ('uploadTime', models.DateTimeField(verbose_name='uploadTime')),
                ('createTime', models.DateTimeField(null=True)),
                ('auditorId', models.BigIntegerField(verbose_name='auditorId')),
                ('auditor', models.CharField(max_length=50, verbose_name='auditor')),
                ('passCount', models.IntegerField(verbose_name='passCount')),
                ('ngCount', models.IntegerField(verbose_name='failCount')),
                ('doneCount', models.IntegerField(verbose_name='doneCount')),
                ('totalCount', models.IntegerField(verbose_name='totalCount')),
            ],
            options={
                'db_table': 't_mde_audit_item',
            },
        ),
    ]
