# Generated by Django 4.1.4 on 2023-02-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws_mqaserver', '0029_mdeaudititemcheckitem_medaudititem'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdeaudititem',
            name='part',
            field=models.CharField(default='', max_length=50, verbose_name='part'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mdeaudititemcheckitem',
            name='part',
            field=models.CharField(default='', max_length=50, verbose_name='part'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mdechecklist',
            name='part',
            field=models.CharField(default='', max_length=50, verbose_name='part'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mdechecklistitem',
            name='part',
            field=models.CharField(default='', max_length=99, verbose_name='Part'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mdeline',
            name='part',
            field=models.CharField(max_length=50, null=True, verbose_name='part'),
        ),
    ]
