# Generated by Django 4.1.4 on 2023-02-10 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aws_mqaserver', '0030_mdeaudititem_part_mdeaudititemcheckitem_part_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessoryaudititemcheckitemgluepoint',
            name='after',
        ),
        migrations.RemoveField(
            model_name='accessoryaudititemcheckitemgluepoint',
            name='before',
        ),
    ]
