# Generated by Django 4.1.4 on 2023-02-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws_mqaserver', '0031_remove_accessoryaudititemcheckitemgluepoint_after_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='displayline',
            name='checkListId_Enclosure',
        ),
        migrations.AddField(
            model_name='displayline',
            name='checkListId',
            field=models.BigIntegerField(null=True, verbose_name='checkListId'),
        ),
    ]
