# Generated by Django 4.1.4 on 2023-02-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws_mqaserver', '0032_remove_displayline_checklistid_enclosure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MILScoreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('auditItemId', models.BigIntegerField(null=True, verbose_name='auditItemId')),
                ('lob', models.CharField(max_length=50, verbose_name='lob')),
                ('site', models.CharField(max_length=50, verbose_name='site')),
                ('productLine', models.CharField(max_length=50, verbose_name='productLine')),
                ('project', models.CharField(max_length=50, verbose_name='project')),
                ('part', models.CharField(max_length=50, verbose_name='part')),
                ('type', models.CharField(max_length=50, verbose_name='type')),
                ('year', models.SmallIntegerField(verbose_name='year')),
                ('month', models.SmallIntegerField(verbose_name='month')),
                ('week', models.SmallIntegerField(verbose_name='week')),
                ('day', models.SmallIntegerField(verbose_name='day')),
                ('quarter', models.SmallIntegerField(verbose_name='quarter')),
                ('vendor', models.CharField(max_length=50, verbose_name='vendor')),
                ('auditType', models.CharField(max_length=99, verbose_name='auditType')),
                ('score', models.FloatField(verbose_name='score')),
                ('range', models.FloatField(verbose_name='range')),
            ],
            options={
                'db_table': 't_sa_mil_score_item',
            },
        ),
        migrations.AddField(
            model_name='militem',
            name='auditType',
            field=models.CharField(default='', max_length=99, verbose_name='auditType'),
            preserve_default=False,
        ),
    ]
