# Generated by Django 4.1.4 on 2023-02-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws_mqaserver', '0033_milscoreitem_militem_audittype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistitemmodule',
            name='checkResult',
        ),
        migrations.RemoveField(
            model_name='checklistitemmodule',
            name='result',
        ),
        migrations.AddField(
            model_name='audititemcheckitemmodule',
            name='checkResult',
            field=models.CharField(max_length=255, null=True, verbose_name='checkResult'),
        ),
    ]
