# Generated by Django 4.1.4 on 2023-02-20 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aws_mqaserver', '0034_remove_checklistitemmodule_checkresult_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milscoreitem',
            name='auditItemId',
        ),
        migrations.RemoveField(
            model_name='milscoreitem',
            name='day',
        ),
        migrations.RemoveField(
            model_name='milscoreitem',
            name='week',
        ),
    ]
