# Generated by Django 4.1.4 on 2023-02-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws_mqaserver', '0036_remove_militem_mildescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitemenclosure',
            name='realSampleSize',
            field=models.CharField(default='', max_length=999, verbose_name='realSampleSize'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklistitemmodule',
            name='realSampleSize',
            field=models.CharField(default='', max_length=255, verbose_name='realSampleSize'),
            preserve_default=False,
        ),
    ]
