# Generated by Django 4.1.4 on 2023-02-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws_mqaserver', '0037_checklistitemenclosure_realsamplesize_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mdeaudititem',
            name='doneCount',
        ),
        migrations.RemoveField(
            model_name='mdeaudititem',
            name='passCount',
        ),
        migrations.RemoveField(
            model_name='mdeaudititem',
            name='totalCount',
        ),
        migrations.AddField(
            model_name='mdeaudititem',
            name='allCount',
            field=models.IntegerField(default=0, verbose_name='allCount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mdeaudititem',
            name='naCount',
            field=models.IntegerField(default=0, verbose_name='naCount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mdeaudititem',
            name='okCount',
            field=models.IntegerField(default=0, verbose_name='okCount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mdeaudititem',
            name='score',
            field=models.IntegerField(default=0, verbose_name='score'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mdeaudititem',
            name='ngCount',
            field=models.IntegerField(verbose_name='ngCount'),
        ),
    ]
