# Generated by Django 4.1.4 on 2023-02-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws_mqaserver', '0039_alter_mdeaudititemcheckitem_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdeaudititemcheckitem',
            name='checkItem_LSL',
            field=models.CharField(max_length=99, verbose_name='LSL'),
        ),
        migrations.AlterField(
            model_name='mdeaudititemcheckitem',
            name='checkItem_USL',
            field=models.CharField(max_length=99, verbose_name='USL'),
        ),
        migrations.AlterField(
            model_name='mdechecklistitem',
            name='LSL',
            field=models.FloatField(max_length=99, verbose_name='LSL'),
        ),
        migrations.AlterField(
            model_name='mdechecklistitem',
            name='USL',
            field=models.CharField(max_length=99, verbose_name='USL'),
        ),
    ]
