# Generated by Django 4.1.4 on 2023-02-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws_mqaserver', '0040_alter_mdeaudititemcheckitem_checkitem_lsl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdechecklistitem',
            name='LSL',
            field=models.CharField(max_length=99, verbose_name='LSL'),
        ),
    ]
