# Generated by Django 4.1.4 on 2023-03-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws_mqaserver', '0042_rename_obaitemid_kappaitemkappaskillscoreitem_kappaitemid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='obaitemscorelossitem',
            name='item',
            field=models.CharField(default='', max_length=30, verbose_name='item'),
            preserve_default=False,
        ),
    ]
