# Generated by Django 4.1.4 on 2023-03-08 18:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aws_mqaserver', '0044_accessoryaudititem_estimatedtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessoryaudititemcheckitemdestructivepoint',
            name='estimatedTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
